# Generated by Django 2.2 on 2019-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktype',
            name='description',
            field=models.TextField(),
        ),
    ]
