# Generated by Django 2.2 on 2019-04-29 09:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20190425_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtype',
            name='options',
        ),
        migrations.AddField(
            model_name='field',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
